name: 'msbuild project generator'
description: 'generates an msbuild parallel project file separating applications and tests'
branding:
  icon: file-text
  color: gray-dark
inputs:
  directory:
    description: 'The directory to scrape for all the project files.'
    required: true
  projectFile:
    description: 'The output file location of the generated project file.'
    required: true
runs:
  using: 'node12'
  main: 'main.js'